version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATASOURCE_URL=jdbc:postgresql://db:5432/elifoot
      - DATASOURCE_USER=postgres
      - DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    volumes:
      - ./src/main/resources/authz.pub:/app/authz.pub:ro
      - ./src/main/resources/authz.pem:/app/authz.pem:ro
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=elifoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 